// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: bidirection.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BiRequest) Reset() {
	*x = BiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidirection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiRequest) ProtoMessage() {}

func (x *BiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bidirection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiRequest.ProtoReflect.Descriptor instead.
func (*BiRequest) Descriptor() ([]byte, []int) {
	return file_bidirection_proto_rawDescGZIP(), []int{0}
}

func (x *BiRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BiResponse) Reset() {
	*x = BiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidirection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiResponse) ProtoMessage() {}

func (x *BiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bidirection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiResponse.ProtoReflect.Descriptor instead.
func (*BiResponse) Descriptor() ([]byte, []int) {
	return file_bidirection_proto_rawDescGZIP(), []int{1}
}

func (x *BiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bidirection_proto protoreflect.FileDescriptor

var file_bidirection_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x09, 0x42, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x42, 0x69,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x43, 0x0a, 0x0e, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x31, 0x0a, 0x12, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x0a, 0x2e, 0x42, 0x69, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x42, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bidirection_proto_rawDescOnce sync.Once
	file_bidirection_proto_rawDescData = file_bidirection_proto_rawDesc
)

func file_bidirection_proto_rawDescGZIP() []byte {
	file_bidirection_proto_rawDescOnce.Do(func() {
		file_bidirection_proto_rawDescData = protoimpl.X.CompressGZIP(file_bidirection_proto_rawDescData)
	})
	return file_bidirection_proto_rawDescData
}

var file_bidirection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bidirection_proto_goTypes = []interface{}{
	(*BiRequest)(nil),  // 0: BiRequest
	(*BiResponse)(nil), // 1: BiResponse
}
var file_bidirection_proto_depIdxs = []int32{
	0, // 0: Bidireactional.BidirectionalHello:input_type -> BiRequest
	1, // 1: Bidireactional.BidirectionalHello:output_type -> BiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bidirection_proto_init() }
func file_bidirection_proto_init() {
	if File_bidirection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bidirection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidirection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bidirection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bidirection_proto_goTypes,
		DependencyIndexes: file_bidirection_proto_depIdxs,
		MessageInfos:      file_bidirection_proto_msgTypes,
	}.Build()
	File_bidirection_proto = out.File
	file_bidirection_proto_rawDesc = nil
	file_bidirection_proto_goTypes = nil
	file_bidirection_proto_depIdxs = nil
}
