// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: server_side.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerSideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SideRes string `protobuf:"bytes,1,opt,name=SideRes,proto3" json:"SideRes,omitempty"`
}

func (x *ServerSideResponse) Reset() {
	*x = ServerSideResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_side_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSideResponse) ProtoMessage() {}

func (x *ServerSideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_side_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSideResponse.ProtoReflect.Descriptor instead.
func (*ServerSideResponse) Descriptor() ([]byte, []int) {
	return file_server_side_proto_rawDescGZIP(), []int{0}
}

func (x *ServerSideResponse) GetSideRes() string {
	if x != nil {
		return x.SideRes
	}
	return ""
}

type ServerSideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SideReq string `protobuf:"bytes,1,opt,name=SideReq,proto3" json:"SideReq,omitempty"`
}

func (x *ServerSideRequest) Reset() {
	*x = ServerSideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_side_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSideRequest) ProtoMessage() {}

func (x *ServerSideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_side_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSideRequest.ProtoReflect.Descriptor instead.
func (*ServerSideRequest) Descriptor() ([]byte, []int) {
	return file_server_side_proto_rawDescGZIP(), []int{1}
}

func (x *ServerSideRequest) GetSideReq() string {
	if x != nil {
		return x.SideReq
	}
	return ""
}

var File_server_side_proto protoreflect.FileDescriptor

var file_server_side_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x69, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x69, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x69, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x69, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x69, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x69, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x32, 0x4c, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65,
	0x12, 0x3e, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x12, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x53, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x13, 0x5a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_side_proto_rawDescOnce sync.Once
	file_server_side_proto_rawDescData = file_server_side_proto_rawDesc
)

func file_server_side_proto_rawDescGZIP() []byte {
	file_server_side_proto_rawDescOnce.Do(func() {
		file_server_side_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_side_proto_rawDescData)
	})
	return file_server_side_proto_rawDescData
}

var file_server_side_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_side_proto_goTypes = []interface{}{
	(*ServerSideResponse)(nil), // 0: ServerSideResponse
	(*ServerSideRequest)(nil),  // 1: ServerSideRequest
}
var file_server_side_proto_depIdxs = []int32{
	1, // 0: ServerSide.ServerSideHello:input_type -> ServerSideRequest
	0, // 1: ServerSide.ServerSideHello:output_type -> ServerSideResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_side_proto_init() }
func file_server_side_proto_init() {
	if File_server_side_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_side_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSideResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_side_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_side_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_side_proto_goTypes,
		DependencyIndexes: file_server_side_proto_depIdxs,
		MessageInfos:      file_server_side_proto_msgTypes,
	}.Build()
	File_server_side_proto = out.File
	file_server_side_proto_rawDesc = nil
	file_server_side_proto_goTypes = nil
	file_server_side_proto_depIdxs = nil
}
